In [4]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'1.3.4'

Welcome to the bootcamp!

In [ ]:
import sys

In [3]:
sys.version

'3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]'

In [6]:
a_py = [10,20,4,23,123,1233]

In [7]:
type(a_py)

list

In [8]:
b_np = np.array([10,20,4,23,123,1233])

In [9]:
type(b_np)

numpy.ndarray

In [10]:
a_py

[10, 20, 4, 23, 123, 1233]

In [11]:
b_np

array([  10,   20,    4,   23,  123, 1233])

# Q: multiply all the numbers by 10

In [15]:
arr = []
for i in a_py:
    arr.append(i * 10)

arr

[100, 200, 40, 230, 1230, 12330]

In [14]:
list(map(lambda i: i*10, a_py))

[100, 200, 40, 230, 1230, 12330]

In [16]:
[i * 10 for i in a_py]

[100, 200, 40, 230, 1230, 12330]

In [17]:
b_np * 10

array([  100,   200,    40,   230,  1230, 12330])

In [25]:
c_np = np.array([1, 2.0, 3])

In [26]:
c_np

array([1., 2., 3.])

In [27]:
c_np.dtype

dtype('float64')

In [30]:
[1, 2.0, 3, 'Andy', {'bootcamp': 'Pands'}]

[1, 2.0, 3, 'Andy', {'bootcamp': 'Pands'}]